apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: host
      mountPath: /data
    - name: pods
      mountPath: /pods
  restartPolicy: Always
  volumes:
  - name: "host"
    hostPath:
      path: /var/lib/docker/containers
  - name: "pods"
    hostPath:
      path: /var/lib/kubelet